// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuDp5D1_EdO0fZXI2IJ3MR6vgzlOrweDs',
    appId: '1:256604439774:ios:779305d6b6e2494823ae4f',
    messagingSenderId: '256604439774',
    projectId: 'skillbridge-bc0e5',
    storageBucket: 'skillbridge-bc0e5.firebasestorage.app',
    iosClientId: '256604439774-8lh2rsl7ishagkgkel76ico2579f2vkm.apps.googleusercontent.com',
    iosBundleId: 'com.skillbridge.skillbridge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKEWYiDme1S4iN8-zTvVKQGtx2Z2Bgmi0',
    appId: '1:256604439774:web:f2978ab8e2d6da5823ae4f',
    messagingSenderId: '256604439774',
    projectId: 'skillbridge-bc0e5',
    authDomain: 'skillbridge-bc0e5.firebaseapp.com',
    storageBucket: 'skillbridge-bc0e5.firebasestorage.app',
    measurementId: 'G-3QT82179RW',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKEWYiDme1S4iN8-zTvVKQGtx2Z2Bgmi0',
    appId: '1:256604439774:web:f2978ab8e2d6da5823ae4f',
    messagingSenderId: '256604439774',
    projectId: 'skillbridge-bc0e5',
    authDomain: 'skillbridge-bc0e5.firebaseapp.com',
    storageBucket: 'skillbridge-bc0e5.firebasestorage.app',
    measurementId: 'G-3QT82179RW',
  );

}