import '../entities/skill_entity.dart';

/// Repository for the skills catalog (Firestore collection: skills).
abstract class SkillRepository {
  /// All skills (catalog). Optionally filter by [category].
  Future<List<SkillEntity>> getSkills({String? category});

  /// Stream of all skills.
  Stream<List<SkillEntity>> watchSkills({String? category});

  /// Single skill by id.
  Future<SkillEntity?> getSkillById(String skillId);

  /// Create a new skill. Id can be generated by the implementation.
  Future<SkillEntity> createSkill(SkillEntity skill);

  /// Update an existing skill.
  Future<void> updateSkill(SkillEntity skill);

  /// Delete a skill.
  Future<void> deleteSkill(String skillId);
}
